/**
 * `@fixmate/api-client` — the single place that knows how to talk to the back
 * end.
 *
 * All four applications import from here and from nowhere else. They get the
 * generated route functions (regenerated by the build, never committed), the
 * fetch wrapper that attaches the access token, the response shapes the back
 * end is expected to return, and one error type.
 *
 * A typical application:
 *
 * ```ts
 * import { createApiClient, createOperations } from '@fixmate/api-client'
 *
 * const client = createApiClient({ baseUrl: process.env.NEXT_PUBLIC_API_URL! })
 * const operations = createOperations(client)
 * const session = await operations.signInUser({ email, password })
 * ```
 */

export { createApiClient, buildQuery } from './http'
export type { ApiClient, ApiClientOptions, HttpMethod, Query, RequestOptions, Route } from './http'

export { ApiError } from './errors'
export type { ApiErrorKind, ApiErrorInit } from './errors'

export { SchemaError } from './schema'
export type { Schema } from './schema'

export { createOperations } from './operations'
export type { Operations, OperationName, SignInInput, SignInResult } from './operations'
